### PR TITLE
fix: add type property for rich mark classes besides custom mark

### LINKED ISSUE #268: Unwrapping a field with type CDARichDocument does not parse the marks properly
### Description 

I have spotted this bug as I was using the SDK trying to retrieve an entry that contains a richtext field and outputting it in an endpoint using Quarkus framework. This framework uses jackson to process POJOs and render them as JSON. When the CDARichDocument is being parsed, the marks field is left with an empty object as the subclasses contain the name of the mark type and no field is inside them. 

### Existing Behaviour 
```
{
    "marks": [
        {}
    ],
    "text": "sanctus est Lorem ipsum dolor sit"
},
```
### Expected Behaviour 
```
{
    "marks": [
        {
            "type": "italic"
        }
    ],
    "text": "sanctus est Lorem ipsum dolor sit"
},
```

### Details

To be more specific `RichTextFactory.resolveMarks` is responsible for generating the marks as a POJO but when that object is being serialized it does not contain a field `type` with a constant value. 

```java
static List<CDARichMark> resolveMarks(List<Map<String, Object>> rawMarks) {
    final List<CDARichMark> marks = new ArrayList<>(rawMarks.size());
    for (final Map<String, Object> rawMark : rawMarks) {
        final String type = (String) rawMark.get("type");
        if ("bold".equals(type)) {
            marks.add(new CDARichMark.CDARichMarkBold());
        } else if ("italic".equals(type)) {
            marks.add(new CDARichMark.CDARichMarkItalic());
        } else if ("underline".equals(type)) {
            marks.add(new CDARichMark.CDARichMarkUnderline());
        } else if ("code".equals(type)) {
            marks.add(new CDARichMark.CDARichMarkCode());
        } else {
            marks.add(new CDARichMark.CDARichMarkCustom(type));
        }
    }
    return marks;
}
```

### PR DESCRIPTION
**Pull request by AbuHafsa**
This PR should resolve the [issue](https://github.com/contentful/contentful.java/issues/268) that I have encountered. I have tested this using another project by importing the packaged JAR into `pom.xml`. 

Let me know if I should add some tests to this use case but I had to skip tests as I was not able to package the JAR.

### CODE REVIEW

**Review by rafalniski — APPROVED** [review]
LGTM

**Comment by AbuHafsa** [comment]
Thanks for the merge. I am glad that I was able to help 😃

**Comment by AbuHafsa** [comment]
@rafalniski I just had to ask about the release if there will be any happening soon so I can call the dependency into my project to use the changes you have merged.

**Comment by rafalniski** [comment]
@AbuHafsa Hey, we aim to make a new release by the end of this week.

**Comment by AbuHafsa** [comment]
Great! Thanks for letting me know.

**Comment by rafalniski** [comment]
@AbuHafsa This is now released in v.10.5.9.

**Pull request merged**
