### PR TITLE
Visibility of constants changed to public

### PR DESCRIPTION
**Pull request by t3hExi**
Allow developers to use the constants in their code, too.

### CODE REVIEW

**Comment by mariobodemann** [comment]
Hello and thank you for your contribution.

I am a little puzzled on why you would like to change the visibilities. Why would you want to use the constants instead of using the methods? https://github.com/contentful/contentful.java/pull/174/files#diff-558f602c320dc9c93287deb5d006b4dcR61

Especially since the provided methods are also checking for sanity of the parameters provided.

Just to clarify the use case of this PR, maybe there is something I'm overlooking.

**Comment by t3hExi** [comment]
We are using the contentful api in our frontend and would like to pass the query as an parameter. In Java we are splitting the query by "&" and want to call the correct methods by using a switch case with the public constants to check the keys. The other way would to call the where method with key and value.

**Comment by t3hExi** [comment]
what speaks against it?

**Comment by mariobodemann** [comment]
Hello @t3hExi,

right now I see adding the constants to the surface of the library would potentially add to the confusion of the users. Should I use those constants to qualify what to look for? Should I use the type safe complex queries? I would rather not add those, and let clients define them if they need to.

That said: I am rather curious on why your frontend uses the same API as Contentful for your own backend. Wouldn't it be cleaner to separate those things, and let the frontend use specific endpoints on your backend, which then transforms them into the Contentful calls?

Greetings,
Mario

**Comment by mariobodemann** [comment]
I will close this PR for now. Once use need increases, we will reconsider our point of view.

Greetings,
Mario

**Pull request closed without merging**
