### PR TITLE
Added paginated query management to get all content types for cache

### PR DESCRIPTION
**Pull request by geco82**
With this change the initial content type sync is done for all content types of the space, calling Contentful API the fewest times possible.

### CODE REVIEW

**Comment by mariobodemann** [comment]
Hey,

thank you for your contribution. I do like the idea a lot! Enabling the cache of content types for more then the first page is a great idea. This would save so many requests, esp. if you have a huge space with a lot of content types.

I am currently working on a 8.0.0 release, and I would be happy to include this. Sadly there are some modifications I would encourage applying.

1) Unit Tests
 I would love to see this tested.

2) Is there a reason to not use the build in pagination?
 Using observe with CMAContentType would allow us to use already existing paths of execution. Did you encounter any issues with that road?

Additionally I was wondering about your use case you addressing. Are you having a space with more then 100 content types, and what is the general usage pattern of those.

And finally: Would you be able to spend the time to address the above mentioned issues, or would you rather have me taking it from here?

**Comment by geco82** [comment]
Hi Mario,
I'm using a space with about 130 content types so, at the moment, the
queries for contents are firing many single content type requests.
For details about my use case in Telepass <https://www.telepass.com> please
refer to Stephen Pastan, Dmytri Kleiner and Kim Bergstrand who are
following my customer.
I considered using ObserveQuery but is its all() method that initializes
itself caching the content types, so I decided to follow the logic already
present using CDAService's Observable<Response<CDAArray>> array(String
space, String type, Map<String, String> query).
I didn't get time to write tests on that and I think I won't have in the
next weeks (vacations! ;-) ).

Thanks

Giacomo

2017-08-03 9:41 GMT+02:00 Mario Bodemann <notifications@github.com>:

**Comment by mariobodemann** [comment]
Hey @geco82,

I am preparing the 8.0.0 release, on https://github.com/contentful/contentful.java/pull/151 including a method-family called `populateContentTypeCache` on the client. This will fetch all the content types if called, and might help you too.

Do you mind taking a look at it? I'm planing on releasing 8.0.0 by the end of this week, and would appreciate feedback for your cause ...

**Comment by geco82** [comment]
Hi Mario,
I'm on holiday right now but I ask to give you a feedback to a colleague of
mine.
Davide is reading us in cc.
Thanks

Giacomo

Il 14/ago/2017 14:08, "Mario Bodemann" <notifications@github.com> ha
scritto:

Hey @geco82 <https://github.com/geco82>,

I am preparing the 8.0.0 release, on #151
<https://github.com/contentful/contentful.java/pull/151> including a
method-family called populateContentTypeCache on the client. This will
fetch all the content types if called, and might help you too.

Do you mind taking a look at it? I'm planing on releasing 8.0.0 by the end
of this week, and would appreciate feedback for your cause ...

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/contentful/contentful.java/pull/152#issuecomment-322173235>,
or mute the thread

**Comment by mariobodemann** [comment]
I integrated a similar solution into https://github.com/contentful/contentful.java/releases/java-sdk-8.0.0 please take a look and let me know what you think. 🎉

Closing this PR for now...

**Pull request closed without merging**
