### PR TITLE
Nullify unresolved links (optional)

### PR DESCRIPTION
**Pull request by tomxor**

### CODE REVIEW

**Comment by grncdr** [comment]
Would it maybe be better to have an `UnresolvedLink extends CDAResource` type? `null` seems a little harsh

**Comment by tomxor** [comment]
@grncdr That introduces the same problem, only instead of a `Map` you'd get a `UnresolvedLink`. Say you have an entry linking to another one, you would be forced to do something like:

```java
CDAResource linkedResource = myEntry.getFields().get("linked");
if (linked instanceof UnresolvedLink) { 
  // ..
} else {
  // ..
}
```

That unfortunately forces to caller to use reflection in order to figure that out :(

**Comment by grncdr** [comment]
That's a fair point. Is there some way that we could return `null` and still let the caller figure out where the broken link is pointing?

**Comment by tomxor** [comment]
I don't think so, AFAIK the way that the iOS SDK deals with this is simply create a blank `CDAEntry`/`CDAAsset`, which potentially could lead to another problem, as one would expect non-null values for required fields and in such cases those would be null.

**Comment by tomxor** [comment]
#57

**Comment by neonichu** [comment]
FWIW, the iOS SDK indeed has blank objects for this case, and a `fetched` property to indicate if an instance is blank or not: <http://cocoadocs.org/docsets/ContentfulDeliveryAPI/1.4.4/Classes/CDAResource.html#//api/name/fetched>

It is not possible to distinguish whether is is indeed a dead link or simply one not included in the response via that property, though.

**Pull request merged**
