### PR TITLE
Add 'type' and 'contentType' parameters to CDAService.

### PR DESCRIPTION
**Pull request by Looney32768**
Add overloads of CDAClient#sync to accept new parameters.
This would make the SDK fit [the docs](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/synchronization/initial-synchronization-of-entries-of-a-specific-content-type/query-entries/console), and save us from loading unnecessary data.

### CODE REVIEW

**Comment by mariobodemann** [comment]
Hey,

thank you for your contribution! It looks great and helps alot! 

There is only one thing missing: Do you think you can add a test for it?

Greetings,
Mario

**Comment by Looney32768** [comment]
I feel the tests are not perfect, but I'm afraid they are the best I'm capable of.

**Comment by Looney32768** [comment]
Hey Mario, thank you for quick reply and such a positive feedback. Is it OK to commit to this PR in case I find something missing?

Victor

**Comment by mariobodemann** [comment]
Hey,

you can keep committing if you like. I just wanted to be open about what is happening from our side next.

**Comment by mariobodemann** [comment]
Hey, 

again thanks so much for the contribution, I will be creating a new PR #168  for it, since the base changed a bit and I will need to make some changes on it.

Thanks for your contribution and please feel free to keep it up. :+1:

**Comment by mariobodemann** [comment]
I did like the initial idea of using `String`s for the creation of the `type` and `content_type` parameter, but I found it can be confusing for the user: Can I use `content_type` also for something else then the `Entry`-type? (Answer: No, it only works on `Entry`)

So I decided to actually use an object to encapsulate the different options and use static creators to provide the user with enough information through the ide on how to create the right type.

I hope I could get you an insight into the decisions and am looking forward for you next contribution, or even feedback on this approach.

**Comment by Looney32768** [comment]
Hi, thanks for explaining the decisions behind the changes - they make sense and are covering my use-case completely. It was a pleasure to contribute:)

**Pull request closed without merging**
